# ./yamato/yamato-config.yml

name: Pack and publish
agent:
    type: Unity::VM
    image: slough-ops/ubuntu-18.04-base:stable
    flavor: b1.small
commands:
    - npm install upm-ci-utils@stable -g --registry https://artifactory.prd.cds.internal.unity3d.com/artifactory/api/npm/upm-npm
    - upm-ci package pack
    - npm install @octokit/core
    - node .yamato/scripts/create-release.js
triggers:
    tags:
        only:
            - /\d+\.\d+\.\d+(-pre\.\d+)?/
