# ./yamato/yamato-config.yml

name: Pack
agent:
    type: Unity::VM
    image: package-ci/ubuntu-22.04:v4
    flavor: b1.large
commands:
    - |
        npm install upm-ci-utils@stable -g --registry https://artifactory.prd.cds.internal.unity3d.com/artifactory/api/npm/upm-npm
        upm-ci package pack --package-path com.unity.xr-content.xr-sim-environments
        curl -L https://artifactory.prd.it.unity3d.com/artifactory/api/security/keypair/default-gpg-key/public | sudo apt-key add -
        sudo sh -c "echo 'deb https://artifactory.prd.it.unity3d.com/artifactory/unity-apt-local bionic main' > /etc/apt/sources.list.d/unity.list"
        sudo apt update
        sudo apt install -y upm-sign
        upm-sign sign "upm-ci~/packages/*.tgz"
artifacts:
    packages:
      paths:
        - "upm-ci~/packages/**"
triggers:
    tags:
        only:
            - /\d+\.\d+\.\d+(-pre\.\d+)?/
